Feature/auth
SecretHouseGame/secrethouse-backend pull request #13
Opened 2022-06-03 13:53 UTC by Maengast

2022-06-03 17:07 UTC, Hikari-rom requested changes
Des petites modifs et des petites questions mais rien de bien méchant :)

2022-06-03 17:07 UTC, Hikari-rom commented on functions/temp/User.js.json
> +{"data":{"propertyOrder":{},"properties":{"id":{"name":"id","reference":"scalar","primary":true,"type":"number"},"username":{"name":"username","reference":"scalar","getter":false,"setter":false,"type
Il est de retour tiens :o 
Pourtant me semblait bien que j'ai vu le gitignore être good 🤔

2022-06-03 17:07 UTC, Hikari-rom commented on functions/src/controllers/authController.ts
> +  console.log(req.body);
P'tit console log

2022-06-03 17:07 UTC, Hikari-rom commented on functions/src/controllers/authController.ts
> +    console.log(user);
Same here, p'tit console log

2022-06-03 17:07 UTC, Hikari-rom commented on functions/src/controllers/commonMiddlewares/authMiddlewares.ts
> +  console.log(token);
P'tit console log ici aussi

2022-06-03 17:11 UTC, Maengast commented on functions/src/index.ts
> +});
Exact mdrr

2022-06-03 17:12 UTC, Maengast commented on functions/temp/User.js.json
> +{"data":{"propertyOrder":{},"properties":{"id":{"name":"id","reference":"scalar","primary":true,"type":"number"},"username":{"name":"username","reference":"scalar","getter":false,"setter":false,"type
je vais fumer ce dossier mdrrr , je vais le bruler xD je vais check du coup mdrr

2022-06-03 17:13 UTC, Maengast commented on functions/src/controllers/authController.ts
> +  console.log(req.body);
je les laisse tant qu'on a pas fini , ca m'aidera pour faire mes logs après et ça me permet de debug si y a un souci sans que j'ai besoin de les rajouter à tout vas. C'est aussi pour ça que j'ai laisser la route de test pour le moment

2022-06-03 17:13 UTC, Maengast commented on functions/src/controllers/authController.ts
> +    console.log(user);
Same as previous comment

2022-06-03 17:13 UTC, Maengast commented on functions/src/controllers/commonMiddlewares/authMiddlewares.ts
> +  console.log(token);
Same as previous comment mdrr

2022-06-07 19:32 UTC, Hikari-rom approved these changes

2022-06-07 19:32 UTC, merged